package react4j.core;

import jsinterop.annotations.JsFunction;

/**
 * A function interface to create component instances.
 * This is typically implemented by the classed generated by the annotation processor and should
 * not be directly implemented.
 *
 * @param <P> the type of the component props.
 * @param <C> the type of the component context.
 */
@FunctionalInterface
@JsFunction
public interface ComponentConstructorFunction<P extends BaseProps, C extends BaseContext>
{
  /**
   * Construct a component based on specified properties.
   *
   * @param props   the component props.
   * @param context the component context.
   * @return the component.
   */
  NativeComponent<P, ?, C> construct( P props, C context );
}
