package react4j.core;

import jsinterop.annotations.JsFunction;

/**
 * A function interface to create component instances.
 * This is typically implemented by the classed generated by the annotation processor and should
 * not be directly implemented.
 */
@FunctionalInterface
@JsFunction
public interface ComponentConstructorFunction<P extends BaseProps, S extends BaseState, C extends BaseContext, I extends NativeComponent<P, S, C>>
{
  /**
   * Construct a component based on specified properties.
   *
   * @param props   the component props.
   * @param context the component context.
   * @return the component.
   */
  I construct( P props, C context );
}
