repositories:
  remote:
   - http://repo1.maven.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/public
   - https://stocksoftware.jfrog.io/stocksoftware/oss

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.12

  shade_task: org.realityforge.ant.shade:ant-shade-task:jar:0.1

  anodoc: org.realityforge.anodoc:anodoc:jar:1.0.0

  javax_jsr305: com.google.code.findbugs:jsr305:jar:3.0.1
  jetbrains_annotations: org.jetbrains:annotations:jar:15.0

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.8.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.2

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:1.0.2
  jsinterop_annotations_sources: com.google.jsinterop:jsinterop-annotations:jar:sources:1.0.2

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0-RC1
  jsinterop_base_sources: com.google.jsinterop:base:jar:sources:1.0.0-RC1

  elemental2_core: com.google.elemental2:elemental2-core:jar:1.0.0-RC1
  elemental2_dom: com.google.elemental2:elemental2-dom:jar:1.0.0-RC1
  elemental2_promise: com.google.elemental2:elemental2-promise:jar:1.0.0-RC1

  arez_annotations: org.realityforge.arez:arez-annotations:jar:gwt:0.49
  arez_core: org.realityforge.arez:arez-core:jar:gwt:0.49
  arez_processor: org.realityforge.arez:arez-processor:jar:0.49
  arez_component: org.realityforge.arez:arez-component:jar:gwt:0.49
  arez_extras: org.realityforge.arez:arez-extras:jar:gwt:0.49
  arez_browser_extras: org.realityforge.arez:arez-browser-extras:jar:gwt:0.49

  braincheck: org.realityforge.braincheck:braincheck:jar:gwt:1.4.0

  javax_inject: javax.inject:javax.inject:jar:1

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.92

  autoservice: com.google.auto.service:auto-service:jar:1.0-rc3
  autocommon: com.google.auto:auto-common:jar:0.8
  javapoet: com.squareup:javapoet:jar:1.8.0
  guava: com.google.guava:guava:jar:21.0

  #test deps
  compile_testing: com.google.testing.compile:compile-testing:jar:0.11
  truth: com.google.truth:truth:jar:0.35

  dagger_core: com.google.dagger:dagger:jar:2.13
  dagger_producers: com.google.dagger:dagger-producers:jar:2.13
  dagger_compiler: com.google.dagger:dagger-compiler:jar:2.13
  googlejavaformat: com.google.googlejavaformat:google-java-format:jar:1.4
  errorprone: com.google.errorprone:javac-shaded:jar:9-dev-r4023-3
  javapoet: com.squareup:javapoet:jar:1.8.0
  guava: com.google.guava:guava:jar:21.0

  javax_inject: javax.inject:javax.inject:jar:1
  javax_inject_sources: javax.inject:javax.inject:jar:sources:1
