repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  shade_task: org.realityforge.ant.shade:ant-shade-task:jar:0.1

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.2.0

  # GWT deps
  gwt_user: org.realityforge.com.google.gwt:gwt-user:jar:2.8.2-v20191108
  gwt_dev: org.realityforge.com.google.gwt:gwt-dev:jar:2.8.2-v20191108

  jsinterop_annotations: org.realityforge.com.google.jsinterop:jsinterop-annotations:jar:2.8.2-v20191108

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  elemental2_core: org.realityforge.com.google.elemental2:elemental2-core:jar:2.27
  elemental2_dom: org.realityforge.com.google.elemental2:elemental2-dom:jar:2.27
  elemental2_promise: org.realityforge.com.google.elemental2:elemental2-promise:jar:2.27

  arez_core: org.realityforge.arez:arez-core:jar:0.165
  arez_processor: org.realityforge.arez:arez-processor:jar:0.165

  braincheck: org.realityforge.braincheck:braincheck:jar:1.25.0

  grim_annotations: org.realityforge.grim:grim-annotations:jar:0.04
  grim_asserts: org.realityforge.grim:grim-asserts:jar:0.04
  grim_processor: org.realityforge.grim:grim-processor:jar:0.04

  javax_json: org.glassfish:javax.json:jar:1.1

  javax_inject: javax.inject:javax.inject:jar:1
  javax_inject_sources: javax.inject:javax.inject:jar:sources:1

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.106

  autocommon: com.google.auto:auto-common:jar:0.10
  javapoet: com.squareup:javapoet:jar:1.12.0
  guava: com.google.guava:guava:jar:27.1-jre

  proton_core: org.realityforge.proton:proton-core:jar:0.30
  proton_qa: org.realityforge.proton:proton-qa:jar:0.30

  #test deps
  compile_testing: com.google.testing.compile:compile-testing:jar:0.18-rf
  truth: com.google.truth:truth:jar:0.45
  junit: junit:junit:jar:4.12
  hamcrest_core: org.hamcrest:hamcrest-core:jar:1.3

  dagger_core: com.google.dagger:dagger:jar:2.25.2
  dagger_producers: com.google.dagger:dagger-producers:jar:2.25.2
  dagger_spi: com.google.dagger:dagger-spi:jar:2.25.2
  dagger_compiler: com.google.dagger:dagger-compiler:jar:2.25.2
  googlejavaformat: com.google.googlejavaformat:google-java-format:jar:1.5
  errorprone: com.google.errorprone:javac-shaded:jar:9-dev-r4023-3
  guava_failureaccess: com.google.guava:failureaccess:jar:1.0.1
  kotlinx_metadata_jvm: org.jetbrains.kotlinx:kotlinx-metadata-jvm:jar:0.1.0
  kotlin_stdlib: org.jetbrains.kotlin:kotlin-stdlib:jar:1.3.50
  kotlin_stdlib_common: org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.3.50

  gir: org.realityforge.gir:gir-core:jar:0.11

  javacsv: net.sourceforge.javacsv:javacsv:jar:2.1

  gwt_symbolmap: org.realityforge.gwt.symbolmap:gwt-symbolmap:jar:0.09

  testng: org.testng:testng:jar:6.11

  jdepend: guru.nidi:jdepend:jar:2.9.5

  revapi_diff: org.realityforge.revapi.diff:revapi-diff:jar:all:0.08
