repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
  jetbrains_annotations: org.realityforge.org.jetbrains.annotations:org.jetbrains.annotations:jar:1.7.0

  # GWT deps
  gwt_user: com.google.gwt:gwt-user:jar:2.9.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.9.0

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:2.0.0

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  akasha: org.realityforge.akasha:akasha-gwt:jar:0.30

  arez_core: org.realityforge.arez:arez-core:jar:0.207
  arez_processor: org.realityforge.arez:arez-processor:jar:0.207
  arez_testng: org.realityforge.arez:arez-extras-testng:jar:0.207

  # Mockito deps
  mockito: org.mockito:mockito-core:jar:4.5.1
  byte_buddy: net.bytebuddy:byte-buddy:jar:1.12.9
  objenesis: org.objenesis:objenesis:jar:3.2

  sting_core: org.realityforge.sting:sting-core:jar:0.27
  sting_processor: org.realityforge.sting:sting-processor:jar:0.27

  braincheck_core: org.realityforge.braincheck:braincheck-core:jar:1.31.0

  grim_annotations: org.realityforge.grim:grim-annotations:jar:0.09
  grim_asserts: org.realityforge.grim:grim-asserts:jar:0.09
  grim_processor: org.realityforge.grim:grim-processor:jar:0.09

  zemeckis: org.realityforge.zemeckis:zemeckis-core:jar:0.14

  javaemul_internal_annotations: org.realityforge.javaemul.internal.annotations:javaemul.internal.annotations:jar:0.01

  javax_json: org.glassfish:javax.json:jar:1.1

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.110

  javapoet: com.squareup:javapoet:jar:1.13.0

  proton_core: org.realityforge.proton:proton-core:jar:0.58
  proton_qa: org.realityforge.proton:proton-qa:jar:0.58

  gir: org.realityforge.gir:gir-core:jar:0.12

  javacsv: net.sourceforge.javacsv:javacsv:jar:2.1

  gwt_symbolmap: org.realityforge.gwt.symbolmap:gwt-symbolmap:jar:0.09

  testng: org.testng:testng:jar:6.11

  jdepend: guru.nidi:jdepend:jar:2.9.5

  revapi_diff: org.realityforge.revapi.diff:revapi-diff:jar:all:0.08
